/**
 * test/corpus-v2.mjs
 * ─────────────────────────────────────────────────────────────────
 * A DELIBERATELY STRATIFIED evaluation corpus, built to fix a
 * recurring limitation found across several rounds of this project's
 * music/semantic evaluation work: EVAL_DATASET/LONG_TEXTS grew
 * organically (hand-written for negation tests, then padded for
 * sentence-count balance) and was never stratified along the axis
 * that turned out to matter most for validating phrase-awareness
 * fixes — IDIOM DENSITY. Three separate analyses (motif-dominance,
 * tenseScore<->leap correlation, and the phrase-awareness fix to
 * intention.js/composition.js) each hit the same wall: "we can't
 * tell if this is a real effect or a corpus artifact." This corpus
 * is generated (not hand-written) directly from real lexicon entries
 * so it's reproducible and explicitly covers a 3-axis grid:
 *
 *   - lengthBucket: '1' | '2' | '3-4' | '5-7' | '8+' sentences
 *   - density: 'pure-word' (only single-word lexicon entries used —
 *       the OLD wordSentimentSign's entire visible world),
 *       'pure-idiom' (only multi-word phrases with NO constituent
 *       word independently in the lexicon — the OLD blind spot,
 *       exactly), or 'mixed' (alternating)
 *   - lang: 'en' | 'fa'
 *
 * Each entry also carries its source 'category' (joy/sadness/fear/
 * anger/calm/hope/love/dark) and 'expectedSign' (+1/-1) from that
 * category's lexicon weight, so downstream evaluation can check
 * DIRECTIONAL correctness (does a fear-built text actually score
 * negative?), not just "some signal was detected."
 *
 * Generated by build-corpus-v2.mjs against the live lexicon files —
 * re-run that script if the lexicon changes and this corpus should
 * track it. Text quality is deliberately utilitarian (concatenated
 * lexicon phrases, not hand-crafted prose) — this corpus exists to
 * stress-test the SIGNAL PATH, not to sound natural.
 */
export const CORPUS_V2 = [
  {
    "text": "Happy.",
    "lengthBucket": "1",
    "density": "pure-word",
    "lang": "en",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "Sorrow.",
    "lengthBucket": "1",
    "density": "pure-word",
    "lang": "en",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "Terror.",
    "lengthBucket": "1",
    "density": "pure-word",
    "lang": "en",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "Hate.",
    "lengthBucket": "1",
    "density": "pure-word",
    "lang": "en",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "Tranquil.",
    "lengthBucket": "1",
    "density": "pure-word",
    "lang": "en",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "Grateful.",
    "lengthBucket": "1",
    "density": "pure-word",
    "lang": "en",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "Tender.",
    "lengthBucket": "1",
    "density": "pure-word",
    "lang": "en",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "Bleak.",
    "lengthBucket": "1",
    "density": "pure-word",
    "lang": "en",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "Over the moon.",
    "lengthBucket": "1",
    "density": "pure-idiom",
    "lang": "en",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "Carrying a lot right now.",
    "lengthBucket": "1",
    "density": "pure-idiom",
    "lang": "en",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "Walking on eggshells.",
    "lengthBucket": "1",
    "density": "pure-idiom",
    "lang": "en",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "Done with this.",
    "lengthBucket": "1",
    "density": "pure-idiom",
    "lang": "en",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "In balance.",
    "lengthBucket": "1",
    "density": "pure-idiom",
    "lang": "en",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "The sky is the limit.",
    "lengthBucket": "1",
    "density": "pure-idiom",
    "lang": "en",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "Into you.",
    "lengthBucket": "1",
    "density": "pure-idiom",
    "lang": "en",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "Nothing matters.",
    "lengthBucket": "1",
    "density": "pure-idiom",
    "lang": "en",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "Feeling marvelous.",
    "lengthBucket": "1",
    "density": "mixed",
    "lang": "en",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "Feeling ignored.",
    "lengthBucket": "1",
    "density": "mixed",
    "lang": "en",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "Butterflies in stomach.",
    "lengthBucket": "1",
    "density": "mixed",
    "lang": "en",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "Seeing red.",
    "lengthBucket": "1",
    "density": "mixed",
    "lang": "en",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "Breathing calmly.",
    "lengthBucket": "1",
    "density": "mixed",
    "lang": "en",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "The best is yet to come.",
    "lengthBucket": "1",
    "density": "mixed",
    "lang": "en",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "You are my heart.",
    "lengthBucket": "1",
    "density": "mixed",
    "lang": "en",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "Nothing endures.",
    "lengthBucket": "1",
    "density": "mixed",
    "lang": "en",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "Vibrant. Hyped.",
    "lengthBucket": "2",
    "density": "pure-word",
    "lang": "en",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "Broken. غم.",
    "lengthBucket": "2",
    "density": "pure-word",
    "lang": "en",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "لرزان. Aghast.",
    "lengthBucket": "2",
    "density": "pure-word",
    "lang": "en",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "عصبانی. وحشی.",
    "lengthBucket": "2",
    "density": "pure-word",
    "lang": "en",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "راحت. Decompressing.",
    "lengthBucket": "2",
    "density": "pure-word",
    "lang": "en",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "شکرگزار. Believing.",
    "lengthBucket": "2",
    "density": "pure-word",
    "lang": "en",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "صمیمی. Endgame.",
    "lengthBucket": "2",
    "density": "pure-word",
    "lang": "en",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "Nothingness. Alienated.",
    "lengthBucket": "2",
    "density": "pure-word",
    "lang": "en",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "Full of vigor. Good vibes only.",
    "lengthBucket": "2",
    "density": "pure-idiom",
    "lang": "en",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "Lump in my throat. In a slump.",
    "lengthBucket": "2",
    "density": "pure-idiom",
    "lang": "en",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "Hyper vigilant. On edge today.",
    "lengthBucket": "2",
    "density": "pure-idiom",
    "lang": "en",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "In my face. Make like a tree.",
    "lengthBucket": "2",
    "density": "pure-idiom",
    "lang": "en",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "It is what it is. Low-key.",
    "lengthBucket": "2",
    "density": "pure-idiom",
    "lang": "en",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "Step by step. Level up.",
    "lengthBucket": "2",
    "density": "pure-idiom",
    "lang": "en",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "Through good and bad. Heart racing.",
    "lengthBucket": "2",
    "density": "pure-idiom",
    "lang": "en",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "Can’t see a way out. Can’t feel anything.",
    "lengthBucket": "2",
    "density": "pure-idiom",
    "lang": "en",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "Living my best life. Exuberant.",
    "lengthBucket": "2",
    "density": "mixed",
    "lang": "en",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "In a rut. Forlorn.",
    "lengthBucket": "2",
    "density": "mixed",
    "lang": "en",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "Can’t shake this feeling. Afraid.",
    "lengthBucket": "2",
    "density": "mixed",
    "lang": "en",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "So done. Snapping.",
    "lengthBucket": "2",
    "density": "mixed",
    "lang": "en",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "In harmony. Poised.",
    "lengthBucket": "2",
    "density": "mixed",
    "lang": "en",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "Next chapter. Promise.",
    "lengthBucket": "2",
    "density": "mixed",
    "lang": "en",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "Heart pounding. Caring.",
    "lengthBucket": "2",
    "density": "mixed",
    "lang": "en",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "No way out. Dying.",
    "lengthBucket": "2",
    "density": "mixed",
    "lang": "en",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "Radiating. Silly. شادمان. شعف.",
    "lengthBucket": "3-4",
    "density": "pure-word",
    "lang": "en",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "Melancholic. Grieving. Gutted. Loneliness.",
    "lengthBucket": "3-4",
    "density": "pure-word",
    "lang": "en",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "Scared. Worried. Frightened. نگرانی.",
    "lengthBucket": "3-4",
    "density": "pure-word",
    "lang": "en",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "Scram. Angry. Resent. Frustration.",
    "lengthBucket": "3-4",
    "density": "pure-word",
    "lang": "en",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "Placid. Mute. Reflective. Tranquility.",
    "lengthBucket": "3-4",
    "density": "pure-word",
    "lang": "en",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "Grateful. Grow. Determined. ایمان.",
    "lengthBucket": "3-4",
    "density": "pure-word",
    "lang": "en",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "Crush. Snuggle. دلبر. دلداده.",
    "lengthBucket": "3-4",
    "density": "pure-word",
    "lang": "en",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "Dead. Shadows. Wounded. ناامید.",
    "lengthBucket": "3-4",
    "density": "pure-word",
    "lang": "en",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "On top of the world. Walking on air. In stitches. Full of life.",
    "lengthBucket": "3-4",
    "density": "pure-idiom",
    "lang": "en",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "In a funk. Heart aches. Feeling forgotten. Choking up.",
    "lengthBucket": "3-4",
    "density": "pure-idiom",
    "lang": "en",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "Stomach in knots. Fight or flight. Losing my mind. Stressed tf out.",
    "lengthBucket": "3-4",
    "density": "pure-idiom",
    "lang": "en",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "Done with this. Blowing my lid. Throwing a fit. Pushing my buttons.",
    "lengthBucket": "3-4",
    "density": "pure-idiom",
    "lang": "en",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "Easy going. Letting go of it. Clear headed. Kicking back.",
    "lengthBucket": "3-4",
    "density": "pure-idiom",
    "lang": "en",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "Brighter days ahead. Shooting for the stars. Every day is a fresh start. Trusting the journey.",
    "lengthBucket": "3-4",
    "density": "pure-idiom",
    "lang": "en",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "My favorite human. My constant. Wild about. You are my anchor.",
    "lengthBucket": "3-4",
    "density": "pure-idiom",
    "lang": "en",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "Nothing remains. Soul tired. Running on fumes. No point anymore.",
    "lengthBucket": "3-4",
    "density": "pure-idiom",
    "lang": "en",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "Feeling incredible. سرزنده. Full of energy. Delight.",
    "lengthBucket": "3-4",
    "density": "mixed",
    "lang": "en",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "Heart hurts. Emptiness. Voice cracking. غمگین.",
    "lengthBucket": "3-4",
    "density": "mixed",
    "lang": "en",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "Freeze response. استرس. Freaking out a little. Hyperventilating.",
    "lengthBucket": "3-4",
    "density": "mixed",
    "lang": "en",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "Seeing red. Screaming. Under my skin. غضب.",
    "lengthBucket": "3-4",
    "density": "mixed",
    "lang": "en",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "Not stressing. Settled. Hanging loose. Ease.",
    "lengthBucket": "3-4",
    "density": "mixed",
    "lang": "en",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "Reaching for the moon. نور. Staying faithful. Trust.",
    "lengthBucket": "3-4",
    "density": "mixed",
    "lang": "en",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "Home to me. Ilysm. You are my sunshine. Embrace.",
    "lengthBucket": "3-4",
    "density": "mixed",
    "lang": "en",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "Checked out. زخم. Disappearing inside. Wrecked.",
    "lengthBucket": "3-4",
    "density": "mixed",
    "lang": "en",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "Lit. Thriving. Delighted. Great. Fun. Lively.",
    "lengthBucket": "5-7",
    "density": "pure-word",
    "lang": "en",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "Hollow. Blue. اندوه. افسرده. Forlorn. Grief.",
    "lengthBucket": "5-7",
    "density": "pure-word",
    "lang": "en",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "خطر. Petrified. Hyperaware. Jittery. Terror. Panic.",
    "lengthBucket": "5-7",
    "density": "pure-word",
    "lang": "en",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "Fuck. Hell. نفرت. Pissed. Enraged. Snapping.",
    "lengthBucket": "5-7",
    "density": "pure-word",
    "lang": "en",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "Content. Gentle. Relax. Mellow. Breezy. نرم.",
    "lengthBucket": "5-7",
    "density": "pure-word",
    "lang": "en",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "شکرگزار. Believing. Hope. Wish. Alive. Motivated.",
    "lengthBucket": "5-7",
    "density": "pure-word",
    "lang": "en",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "Affectionate. Sweetheart. Tender. Infatuated. Flirting. عاشق.",
    "lengthBucket": "5-7",
    "density": "pure-word",
    "lang": "en",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "سایه. Disintegrating. Numb. Claustrophobic. Cold. Hopeless.",
    "lengthBucket": "5-7",
    "density": "pure-word",
    "lang": "en",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "Full of vim. Counting down the days. On a roll. All smiles today. Having a ball. Feeling splendid.",
    "lengthBucket": "5-7",
    "density": "pure-idiom",
    "lang": "en",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "Weight of the world. Feeling morose. In a hole. Low key struggling. Off today. از دست دادن.",
    "lengthBucket": "5-7",
    "density": "pure-idiom",
    "lang": "en",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "On edge today. On edge. Under the gun. Sweaty palms. Stressed about it. On guard.",
    "lengthBucket": "5-7",
    "density": "pure-idiom",
    "lang": "en",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "In my face. Make like a tree. Absolutely done. Fed up. At the end of my tether. Going off.",
    "lengthBucket": "5-7",
    "density": "pure-idiom",
    "lang": "en",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "Deep breath. Easy does it. Settling in. All is well. In sync. Breathing calmly.",
    "lengthBucket": "5-7",
    "density": "pure-idiom",
    "lang": "en",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "Never losing heart. Keeping on keeping on. Sooner or later. Positive outlook. On the come up. Looking ahead.",
    "lengthBucket": "5-7",
    "density": "pure-idiom",
    "lang": "en",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "You are my soul. My queen. Through thick and thin. Butterflies in my stomach. My person. Can’t get enough of you.",
    "lengthBucket": "5-7",
    "density": "pure-idiom",
    "lang": "en",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "Shell of who I was. At the end of the line. Life is meaningless. Black hole. Hollowed out. Going through it.",
    "lengthBucket": "5-7",
    "density": "pure-idiom",
    "lang": "en",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "Good vibes only. Amazing. Life is good. Pumped. Feeling fabulous. Jubilant.",
    "lengthBucket": "5-7",
    "density": "mixed",
    "lang": "en",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "Feeling dismal. ملال. Rough patch. Cry. Heart aches. Empty.",
    "lengthBucket": "5-7",
    "density": "mixed",
    "lang": "en",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "On pins and needles. Distressed. Sweating bullets. Danger. On watch. کابوس.",
    "lengthBucket": "5-7",
    "density": "mixed",
    "lang": "en",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "So done. Seething. Sick and tired. Vamoose. Going ballistic. Resentment.",
    "lengthBucket": "5-7",
    "density": "mixed",
    "lang": "en",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "Laid back. Unwind. In a good headspace. صلح. Level headed. Unruffled.",
    "lengthBucket": "5-7",
    "density": "mixed",
    "lang": "en",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "One day at a time. Promise. Things will improve. Driven. Eyes on the prize. رشد.",
    "lengthBucket": "5-7",
    "density": "mixed",
    "lang": "en",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "Holding hands. Honey. Heart racing. مهربان. You’re my person. Darling.",
    "lengthBucket": "5-7",
    "density": "mixed",
    "lang": "en",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "At the end of the road. Invisible. Existential crisis. Abyss. Can’t see a way out. مرگ.",
    "lengthBucket": "5-7",
    "density": "mixed",
    "lang": "en",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "Laugh. Sunny. Thrilled. Jazzed. Overjoyed. Glowing. Goofy. خنده. مسرور.",
    "lengthBucket": "8+",
    "density": "pure-word",
    "lang": "en",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "اندوهگین. Aching. Crying. Shattered. Emptiness. Depressed. غمگین. شکسته. Disheartened.",
    "lengthBucket": "8+",
    "density": "pure-word",
    "lang": "en",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "Fear. Anxiety. Unsafe. وحشت. لرزان. Aghast. Apprehensive. Distressed. Anxious.",
    "lengthBucket": "8+",
    "density": "pure-word",
    "lang": "en",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "Boiling. Irate. Skedaddle. Fury. Bitter. Screaming. Dammit. غضب. انفجار.",
    "lengthBucket": "8+",
    "density": "pure-word",
    "lang": "en",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "Unwinding. سکوت. هدوء. Anchored. Unflappable. Idyllic. Restful. Mindful. Settled.",
    "lengthBucket": "8+",
    "density": "pure-word",
    "lang": "en",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "Grateful. Grow. Determined. ایمان. شروع. Onward. Future. Gratitude. Growth.",
    "lengthBucket": "8+",
    "density": "pure-word",
    "lang": "en",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "Boo. Partner. صمیمی. Endgame. Cherish. Soulmate. Honey. Valentine. مهربان.",
    "lengthBucket": "8+",
    "density": "pure-word",
    "lang": "en",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "Ghostlike. Dying. Shadow. Wound. مردن. Sinking. Desolate. Fragmented. Ghostlike.",
    "lengthBucket": "8+",
    "density": "pure-word",
    "lang": "en",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "This made my day. In seventh heaven. Cracking up. Feeling rich. Raring to go. Glow up. Best mood ever. This made my day. In seventh heaven.",
    "lengthBucket": "8+",
    "density": "pure-idiom",
    "lang": "en",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "In my feelings. Down bad. Feeling down. Sky is gray. Voice breaking. Feeling glum. In a rut. Emotional damage. Struggling a bit.",
    "lengthBucket": "8+",
    "density": "pure-idiom",
    "lang": "en",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "Fight or flight. Losing my mind. Stressed tf out. Holding my breath. Stressed out. Butterflies in stomach. Freeze response. Short of breath. Freaking out a little.",
    "lengthBucket": "8+",
    "density": "pure-idiom",
    "lang": "en",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "Done with this. Blowing my lid. Throwing a fit. Pushing my buttons. Get out of my face. Done with this nonsense. About to lose it. Over it. Seeing red.",
    "lengthBucket": "8+",
    "density": "pure-idiom",
    "lang": "en",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "Laid-back. Hanging loose. No stress. No rush. Going with the flow. In harmony. Deep breath. Easy does it. Settling in.",
    "lengthBucket": "8+",
    "density": "pure-idiom",
    "lang": "en",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "Better days coming. Staying positive. Positive vibes. There is a way. Something good is about to happen. Hanging in there. Step by step. Level up. Pushing forward.",
    "lengthBucket": "8+",
    "density": "pure-idiom",
    "lang": "en",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "Heart melting. Forever mine. Simping hard. You’re it for me. Crazy about. You are my rock. My angel. Sharing moments. For better or worse.",
    "lengthBucket": "8+",
    "density": "pure-idiom",
    "lang": "en",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "Done with everything. Beyond repair. Give up feeling. No end in sight. Given up on life. Nothing left. Done with everything. Beyond repair. Give up feeling.",
    "lengthBucket": "8+",
    "density": "pure-idiom",
    "lang": "en",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "Walking on air. Jolly. Full of life. Grinning. Main character energy. سرخوش. On top of the world. Thriving. In stitches.",
    "lengthBucket": "8+",
    "density": "mixed",
    "lang": "en",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "Need a moment. Miserable. Life is gray. Gloom. Feeling morose. سنگین. Low key struggling. Grieving. از دست دادن.",
    "lengthBucket": "8+",
    "density": "mixed",
    "lang": "en",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "Short of breath. نگرانی. Knot in my stomach. Spiraling. Shaking like a leaf. Afraid. Gasping for air. Trembling. Dreading this.",
    "lengthBucket": "8+",
    "density": "mixed",
    "lang": "en",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "Seeing red. Mad. Under my skin. Fucking. Over this already. کینه. At my wit's end. Outraged. Having a meltdown.",
    "lengthBucket": "8+",
    "density": "mixed",
    "lang": "en",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "Letting go. Steady. Breathing easy. Bucolic. In balance. Nirvana. Laid back. Soft. In a good headspace.",
    "lengthBucket": "8+",
    "density": "mixed",
    "lang": "en",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "Keeping my chin up. نور. Where there is a will there is a way. Trust. Hanging tough. Freedom. Next chapter. امید. Staying positive.",
    "lengthBucket": "8+",
    "density": "mixed",
    "lang": "en",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "My everything. Loving. My constant. Caring. You are my anchor. عشق. Building a life. Love. You make me whole.",
    "lengthBucket": "8+",
    "density": "mixed",
    "lang": "en",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "Running on fumes. تاریک. Hit a wall. Crumbling. Nothing remains. Weightless. Running on fumes. Despair. Hit a wall.",
    "lengthBucket": "8+",
    "density": "mixed",
    "lang": "en",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "قانع.",
    "lengthBucket": "1",
    "density": "pure-word",
    "lang": "fa",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "عذاب.",
    "lengthBucket": "1",
    "density": "pure-word",
    "lang": "fa",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "لرزان.",
    "lengthBucket": "1",
    "density": "pure-word",
    "lang": "fa",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "مخالفتم.",
    "lengthBucket": "1",
    "density": "pure-word",
    "lang": "fa",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "استراحت.",
    "lengthBucket": "1",
    "density": "pure-word",
    "lang": "fa",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "امید.",
    "lengthBucket": "1",
    "density": "pure-word",
    "lang": "fa",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "جفتمی.",
    "lengthBucket": "1",
    "density": "pure-word",
    "lang": "fa",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "تباه.",
    "lengthBucket": "1",
    "density": "pure-word",
    "lang": "fa",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "کارا رو به راهه.",
    "lengthBucket": "1",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "بغضم ترکید.",
    "lengthBucket": "1",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "حس میکنم خطری هست.",
    "lengthBucket": "1",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "بهانه میگیرم.",
    "lengthBucket": "1",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "هرچی بشه.",
    "lengthBucket": "1",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "حقته که بشه.",
    "lengthBucket": "1",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "دلبسته‌تم.",
    "lengthBucket": "1",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "چرا ادامه بدم.",
    "lengthBucket": "1",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "حس میکنم زنده‌ام.",
    "lengthBucket": "1",
    "density": "mixed",
    "lang": "fa",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "دیگه توانی ندارم.",
    "lengthBucket": "1",
    "density": "mixed",
    "lang": "fa",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "ترسیدم واقعا.",
    "lengthBucket": "1",
    "density": "mixed",
    "lang": "fa",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "ستیزه‌جو.",
    "lengthBucket": "1",
    "density": "mixed",
    "lang": "fa",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "کاری به کسی ندارم.",
    "lengthBucket": "1",
    "density": "mixed",
    "lang": "fa",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "راه حل پیدا میشه.",
    "lengthBucket": "1",
    "density": "mixed",
    "lang": "fa",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "مال منی همیشه.",
    "lengthBucket": "1",
    "density": "mixed",
    "lang": "fa",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "هیچکس نیست کمکم کنه.",
    "lengthBucket": "1",
    "density": "mixed",
    "lang": "fa",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "باکلاسه. خفنه.",
    "lengthBucket": "2",
    "density": "pure-word",
    "lang": "fa",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "دلشکسته. تنها.",
    "lengthBucket": "2",
    "density": "pure-word",
    "lang": "fa",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "ترسو. واهمه.",
    "lengthBucket": "2",
    "density": "pure-word",
    "lang": "fa",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "خشمگین. بدعنق.",
    "lengthBucket": "2",
    "density": "pure-word",
    "lang": "fa",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "قناعت. دلنشین.",
    "lengthBucket": "2",
    "density": "pure-word",
    "lang": "fa",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "میجنگم. باور.",
    "lengthBucket": "2",
    "density": "pure-word",
    "lang": "fa",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "عاشقت. مهربونی.",
    "lengthBucket": "2",
    "density": "pure-word",
    "lang": "fa",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "پوچ. رهاشده.",
    "lengthBucket": "2",
    "density": "pure-word",
    "lang": "fa",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "حس میکنم بال دارم. خدا رو صد هزار مرتبه شکر.",
    "lengthBucket": "2",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "روحیم خراب شد. دلم نمیخواد هیچی.",
    "lengthBucket": "2",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "می‌ترسم خیلی. هول شدم.",
    "lengthBucket": "2",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "دیگه نمیخوام ببینمت. اعصاب نذاشتی برام.",
    "lengthBucket": "2",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "باورش دارم. دیگه فکرم مشغول نیست.",
    "lengthBucket": "2",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "بذار زمان بگذره درست میشه. میدونم درست میشه.",
    "lengthBucket": "2",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "هیچکس مثل تو نیست. همیشه دوست دارم.",
    "lengthBucket": "2",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "ته خطم واقعا. روحم مرده انگار.",
    "lengthBucket": "2",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "ممنونم از خدا. بشاش.",
    "lengthBucket": "2",
    "density": "mixed",
    "lang": "fa",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "گریم گرفته. عزا.",
    "lengthBucket": "2",
    "density": "mixed",
    "lang": "fa",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "شوکه شدم. ترسو.",
    "lengthBucket": "2",
    "density": "mixed",
    "lang": "fa",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "روانیم کردی. غضبناک.",
    "lengthBucket": "2",
    "density": "mixed",
    "lang": "fa",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "آسوده شدم از ته دلم. متعادل.",
    "lengthBucket": "2",
    "density": "mixed",
    "lang": "fa",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "میدونم بهتر میشه. محکمم.",
    "lengthBucket": "2",
    "density": "mixed",
    "lang": "fa",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "هیچوقت فراموشت نمیکنم. همدم.",
    "lengthBucket": "2",
    "density": "mixed",
    "lang": "fa",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "دیگه رمقی نمونده تو تنم. فروپاشی.",
    "lengthBucket": "2",
    "density": "mixed",
    "lang": "fa",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "سرزنده. مسرور. ذوق. شادمانی.",
    "lengthBucket": "3-4",
    "density": "pure-word",
    "lang": "fa",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "سوگ. اشکام. تنهاییام. مغموم.",
    "lengthBucket": "3-4",
    "density": "pure-word",
    "lang": "fa",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "خطرناک. نگرانتم. مضطرب. لرزان.",
    "lengthBucket": "3-4",
    "density": "pure-word",
    "lang": "fa",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "خشن. بدبین. بیزار. خشن.",
    "lengthBucket": "3-4",
    "density": "pure-word",
    "lang": "fa",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "باثبات. تفریح. ریلکس. صبور.",
    "lengthBucket": "3-4",
    "density": "pure-word",
    "lang": "fa",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "استوارم. اشتیاق. استوار. نیرومند.",
    "lengthBucket": "3-4",
    "density": "pure-word",
    "lang": "fa",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "دلبستمی. یارم. ماهم. عاشقت.",
    "lengthBucket": "3-4",
    "density": "pure-word",
    "lang": "fa",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "ناامید. خرابه. مایوس. متروک.",
    "lengthBucket": "3-4",
    "density": "pure-word",
    "lang": "fa",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "کیفور شدم واقعا. اطرافم پر از خوشیه. کیفور شدیم باهم. آرزوم برآورده شد.",
    "lengthBucket": "3-4",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "انرژی ندارم هیچ. تنهام گذاشتن. رنج میبرم. درد دارم.",
    "lengthBucket": "3-4",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "زانوهام سست شد. فشار دارم. خیس عرق شدم. یه چیزی میگه خطرناکه.",
    "lengthBucket": "3-4",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "داد و بیداد راه انداختم. واقعا لجم گرفته. دیوونم کردی واقعا. ازت متنفرم واقعا.",
    "lengthBucket": "3-4",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "هرچی بشه خوبه. هیچی نگرانم نمیکنه. قلبم آرومه کامل. فقط دارم نفس میکشم آروم.",
    "lengthBucket": "3-4",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "توان دارم. باید ادامه بدم. فردا یه شانس جدیده. میرسم بهش بالاخره.",
    "lengthBucket": "3-4",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "دلبسته شما شدم. تکیه‌گاهم. همه چیزمی. قلبم برات میزنه.",
    "lengthBucket": "3-4",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "همه چی بی‌فایدس. طاقتم تموم شد. از پا در اومدم. حس نمیکنم چیزیو.",
    "lengthBucket": "3-4",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "هیچی کم ندارم الان. طرب. کیف کردیم باهم. بمبه.",
    "lengthBucket": "3-4",
    "density": "mixed",
    "lang": "fa",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "همه رفتن از کنارم. محزون. رنج دارم. اندوه.",
    "lengthBucket": "3-4",
    "density": "mixed",
    "lang": "fa",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "فشار روم زیاده. خطرناک. نمیدونم چرا ولی میترسم. مضطرب.",
    "lengthBucket": "3-4",
    "density": "mixed",
    "lang": "fa",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "حرصم دراومده. دعوایی. نفرتت تو دلم نشسته. نارضایتیم.",
    "lengthBucket": "3-4",
    "density": "mixed",
    "lang": "fa",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "ذهنم ساکته کامل. متین. خودمو رها کردم. دلنشین.",
    "lengthBucket": "3-4",
    "density": "mixed",
    "lang": "fa",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "باید بجنگم. امیدوارم. مطمئنم درست میشه. یقین.",
    "lengthBucket": "3-4",
    "density": "mixed",
    "lang": "fa",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "قربونت برم. دلبسته. دلم برات پر میزنه. جونمی.",
    "lengthBucket": "3-4",
    "density": "mixed",
    "lang": "fa",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "همه چی تاریکه دورم. داغونم. بی‌حسم کاملا. سرگردانم.",
    "lengthBucket": "3-4",
    "density": "mixed",
    "lang": "fa",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "وجد. توپ. آتیشه. شادیم. بشاش. خرسند.",
    "lengthBucket": "5-7",
    "density": "pure-word",
    "lang": "fa",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "گریان. ازپاافتاده. درد. پکرم. دردام. دلتنگیام.",
    "lengthBucket": "5-7",
    "density": "pure-word",
    "lang": "fa",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "ترسناک. نگرانشم. نگران. ترسو. واهمه. هراسان.",
    "lengthBucket": "5-7",
    "density": "pure-word",
    "lang": "fa",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "بداخلاق. مخالف. عصبانی. بداخلاق. مخالف. عصبانی.",
    "lengthBucket": "5-7",
    "density": "pure-word",
    "lang": "fa",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "باوقار. رضایت. لطیف. آهسته. خونسرد. آسایش.",
    "lengthBucket": "5-7",
    "density": "pure-word",
    "lang": "fa",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "مصممم. آرزو. مثبت. قهرمان. استوارم. اشتیاق.",
    "lengthBucket": "5-7",
    "density": "pure-word",
    "lang": "fa",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "شیفته. صمیمیت. عزیزدلمی. دلبستمی. یارم. ماهم.",
    "lengthBucket": "5-7",
    "density": "pure-word",
    "lang": "fa",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "سرگردانم. نابود. فروپاشی. ویرانه. ناامید. خرابه.",
    "lengthBucket": "5-7",
    "density": "pure-word",
    "lang": "fa",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "حال کردیم اون شب. عجب ذوقی. شانس آوردیم. رومون سفیده. می‌خندم. عجب حالی.",
    "lengthBucket": "5-7",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "دلم گرفته. خسته شدم از این دنیا. درد بی‌نصیبی. زجر هر روزه. حالم گرفته‌ست. غمم عمیقه.",
    "lengthBucket": "5-7",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "حس میکنم خطری هست. نگرانم شدید. از فکرش هم میترسم. دلواپسم برات. قلبم تند میزنه. قالب تهی کردم.",
    "lengthBucket": "5-7",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "خون به جیگرم شده. از حالت عادی دراومدم. خشمگینم شدید. از این وضع بیزارم. از این وضع خستم شدیدا. همش دعواست بینمون.",
    "lengthBucket": "5-7",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "هیچی اذیتم نمیکنه الان. اعتماد دارم به خودم. نفس عمیق بکش. خودتو اذیت نکن. هرچی بشه. سرم پایینه.",
    "lengthBucket": "5-7",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "دلم روشنه به فردا. رد میشه این دوره. باور دارم درست میشه. حتما درست میشه. صبر کن درست میشه. حقته که بشه.",
    "lengthBucket": "5-7",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "جونمو میدم برات. دلم برات تنگ شده بود. صدات تو گوشمه. همیشه هوامو داری. می‌بوسمت. تنهام نذار.",
    "lengthBucket": "5-7",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "چرا باید ادامه بدم. دیگه راهی نیست. چرا زنده‌ام. همه تنهام گذاشتن. ویران شدم. پوچی محضه.",
    "lengthBucket": "5-7",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "چه شوقی. خوشیم. روزی نیست. بشکن. چه حالی. سرور.",
    "lengthBucket": "5-7",
    "density": "mixed",
    "lang": "fa",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "نمیخوام هیچی ببینم. دلتنگم. دل‌خسته‌ام. غمگین. دلم ریش شده کامل. ازپاافتاده.",
    "lengthBucket": "5-7",
    "density": "mixed",
    "lang": "fa",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "ترسیدم واقعا. ترسناک. نگرانتم زیاد. نگران. می‌ترسم چیزی بشه. واهمه.",
    "lengthBucket": "5-7",
    "density": "mixed",
    "lang": "fa",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "حرصم گرفته زیاد. بدجنس. خشمگینم از ته دل. آتشی. خون به جیگر شدم. ناراضی.",
    "lengthBucket": "5-7",
    "density": "mixed",
    "lang": "fa",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "باور دارم به خودم. نرم. زیاد فکر نکن. تفریح. کاری به کسی ندارم. صبور.",
    "lengthBucket": "5-7",
    "density": "mixed",
    "lang": "fa",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "پشت هر سختی یه آسونیه. نیرومند. بالاخره درست میشه. باور. لیاقتشو داری. امیدوارم.",
    "lengthBucket": "5-7",
    "density": "mixed",
    "lang": "fa",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "کجایی نبودی دلم گرفت. عشقم. قدرتو میدونم. زندگیم. مال منی. گرمی.",
    "lengthBucket": "5-7",
    "density": "mixed",
    "lang": "fa",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "تهی شدم. متروک. همه فراموشم کردن. رهاشده. هیچی حس نمیکنم دیگه. داغونم.",
    "lengthBucket": "5-7",
    "density": "mixed",
    "lang": "fa",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "میخندونیم. شنگول. رقص. شوق. طرب. باحال. بمبه. خوشحالیم. خندون.",
    "lengthBucket": "8+",
    "density": "pure-word",
    "lang": "fa",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "بغض. جراحتام. ناراحت. اشکبار. شکسته. رنج. دلگیرم. رنجام. حسرتام.",
    "lengthBucket": "8+",
    "density": "pure-word",
    "lang": "fa",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "وحشتناک. نگرانم. دلواپس. خطرناک. نگرانتم. مضطرب. لرزان. دلهره. ترسیده.",
    "lengthBucket": "8+",
    "density": "pure-word",
    "lang": "fa",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "لجباز. کلافه. غضبناک. لجباز. کلافه. غضبناک. لجباز. کلافه. غضبناک.",
    "lengthBucket": "8+",
    "density": "pure-word",
    "lang": "fa",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "صبور. اطمینان. خلوت. راحت. بردبار. اعتماد. سکوت. آسوده. متین.",
    "lengthBucket": "8+",
    "density": "pure-word",
    "lang": "fa",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "توانا. میکشم. اعتقاد. پیروز. مصممم. آرزو. مثبت. قهرمان. استوارم.",
    "lengthBucket": "8+",
    "density": "pure-word",
    "lang": "fa",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "جیگرم. معشوقم. امیدم. شیفته. صمیمیت. عزیزدلمی. دلبستمی. یارم. ماهم.",
    "lengthBucket": "8+",
    "density": "pure-word",
    "lang": "fa",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "رهاشده. گمشده. داغونم. تباه. سرگردانم. نابود. فروپاشی. ویرانه. ناامید.",
    "lengthBucket": "8+",
    "density": "pure-word",
    "lang": "fa",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "باهم میخندیم. حال میده. حال کردم باهاش. انرژی گرفتم. توپ توپم. حرف نداره. جون میده. از خوشحالی بال درآوردم. خوش بگذره.",
    "lengthBucket": "8+",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "خسته‌ام از همه چیز. روزای سختیه. تنهاییم آزارم میده. خستگیم از جنس دیگه‌ایه. از پا دراومدم کامل. دیگه توانی ندارم. دلمرده‌ام. ریخت حالم. حوصله ندارم اصلا.",
    "lengthBucket": "8+",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "می‌ترسم خیلی. هول شدم. دلشوره دارم امتحان. از ناشناخته میترسم. هنوز میلرزم. رنگم پریده. چشمام از حدقه دراومد. حس میکنم چیزی نزدیکه. ترسیدم واقعا.",
    "lengthBucket": "8+",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "دارم از حرص میمیرم. به آخر خط رسیدم باهاش. طاقتم طاق شده کلا. خرده میگیرم. عصبیم خیلی. بسه دیگه. ازت متنفرم. گمشو از جلو چشمام. حرصم گرفت بدجور.",
    "lengthBucket": "8+",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "عجله نکن. سبک شدم. تنها نشستم آروم. فکرشو نمیکنم دیگه. باورش دارم. دیگه فکرم مشغول نیست. دلم میخواد هیچی نگم. آروم پیش میرم. مشکلی نیست اصلا.",
    "lengthBucket": "8+",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "امیدوارم بشه. ادامه بده. بهت میرسه بالاخره. خدا بزرگتره. یکم دیگه صبر کن. بذار زمان بگذره درست میشه. میدونم درست میشه. راه مشخصه. یه روزی دارم.",
    "lengthBucket": "8+",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "ممنونتم که هستی. دلم آغوشتو میخواد. برای هم ساخته شدیم. حضورت قویم میکنه. تو جونی. تو آرامشی. تو خورشیدی. برای تو میمیرم. قلبم مال توعه.",
    "lengthBucket": "8+",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "هیچکس نیست درکم کنه. تباه شدم. دیگه رمقی نیست. امیدم به صفر رسیده. نفس کشیدن سخته برام. دیگه چیزی برام رنگی نیست. همه چی پوچه. راه فراری نیست. به آخر خط رسیدم.",
    "lengthBucket": "8+",
    "density": "pure-idiom",
    "lang": "fa",
    "category": "dark",
    "expectedSign": -1
  },
  {
    "text": "کیف داره. نشاط. باحاله خیلی. عالیه. یه چیز دیگه‌ست. ذوقیم. پر از انرژیم. مسرور. مدام میخندم.",
    "lengthBucket": "8+",
    "density": "mixed",
    "lang": "fa",
    "category": "joy",
    "expectedSign": 1
  },
  {
    "text": "قلبم درد میکنه. تنها. روزای سختی رو میگذرونم. زجر. دلم گرفته حسابی. جراحتام. اعصابم نابود شد. اشکبار. قلبم درد گرفت.",
    "lengthBucket": "8+",
    "density": "mixed",
    "lang": "fa",
    "category": "sadness",
    "expectedSign": -1
  },
  {
    "text": "شوکه شدم. وحشتناک. دستام میلرزه. دلواپس. پاهام سست شده. نگرانتم. فکرم مشغوله. لرزان. ذهنم پر از فکرای بد شده.",
    "lengthBucket": "8+",
    "density": "mixed",
    "lang": "fa",
    "category": "fear",
    "expectedSign": -1
  },
  {
    "text": "بریدم ازش کاملا. دشمن. شکایت دارم. پرخاشگر. دیگه تمومش کن. مخالفتم. اعصاب نذاشتی برام. دشمن. جیگرمو خون کردی.",
    "lengthBucket": "8+",
    "density": "mixed",
    "lang": "fa",
    "category": "anger",
    "expectedSign": -1
  },
  {
    "text": "از دلشوره در اومدم. ساکت. آروم گرفتم بالاخره. رضایت. آسوده شدم از ته دلم. آهسته. هرچی پیش بیاد قبوله. آسایش. سبک شدم درونی.",
    "lengthBucket": "8+",
    "density": "mixed",
    "lang": "fa",
    "category": "calm",
    "expectedSign": 1
  },
  {
    "text": "رهاش نکن. قهرمان. خدا نگهدار. اشتیاق. با گذر زمان بهتر میشه. نیرومند. نابود نمیشم. باور. دلیلی برای ناامیدی نیست.",
    "lengthBucket": "8+",
    "density": "mixed",
    "lang": "fa",
    "category": "hope",
    "expectedSign": 1
  },
  {
    "text": "می‌خوامت کنارم. مفتون. میخوام همیشه کنارم باشی. دیوونتم. تو امنیتی. محبوبم. برای تو زنده‌ام. دلبسته. همیشه فکرمی.",
    "lengthBucket": "8+",
    "density": "mixed",
    "lang": "fa",
    "category": "love",
    "expectedSign": 1
  },
  {
    "text": "گمشده‌ام. ویرانه. روحم مرده انگار. خرابه. بی‌معنا. متروک. خفه شدم تو این وضع. رهاشده. فایده این همه تلاش چیه.",
    "lengthBucket": "8+",
    "density": "mixed",
    "lang": "fa",
    "category": "dark",
    "expectedSign": -1
  }
];
