/**
 * lexicon-en.js
 * English-language emotion lexicon — base word/weight/tense mappings.
 * Persian colloquial words are merged at runtime from lexicon-fa-colloquial.js.
 */
export const EMOTION_LEXICON = {
  joy: { weight: 1.1, tense: 0, words: [
    'happy','joy','joyful','delight','delighted','glad','cheerful','elated','bliss','blissful',
    'wonderful','great','fantastic','amazing','laugh','laughing','smile','smiling','fun','playful',
    'excited','sunny','bright','radiant','vibrant','lively',
    'stoked','pumped','thrilled','buzzing','chuffed','hyped','giddy','tickled','ecstatic',
    'jazzed','psyched','jolly','merry','gleeful','giggling',
    'jubilant','overjoyed','cheery','bubbly','perky','spirited',
    'exuberant','radiating','glowing','beaming','grinning','chuckling','celebratory',
    'festive','silly','goofy','carefree','lighthearted','euphoric',
    'شاد','خوشحال','شادمان','خنده','لبخند','سرخوش','بانمک','هیجان','شور','شعف','مسرور','سرزنده',
    'pumped up','on top of the world','riding high','over the moon','in high spirits',
    'having a blast','having a ball','living it up','on cloud nine','in seventh heaven',
    'walking on air','feeling fantastic','feeling great','feeling awesome','feeling amazing',
    'feeling wonderful','feeling incredible','feeling marvelous','feeling splendid','feeling fabulous',
    'on fire','lit','vibing','grooving','cruising','soaring','floating','gliding',
    'beaming with joy','grinning from ear to ear','smiling ear to ear','laughing out loud',
    'cracking up','dying of laughter','in stitches','rolling on the floor',
    'having the time of my life','best day ever','couldn\'t be happier','life is good',
    'feeling blessed','feeling grateful','feeling thankful','feeling lucky','feeling rich',
    'full of life','full of energy','full of pep','full of vim','full of vigor',
    'bright eyed','bushy tailed','raring to go','ready for anything','can\'t wait',
    'pumped about it','excited about it','looking forward to it','counting down the days',
  ]},
  love: { weight: 1.0, tense: 0, words: [
    'love','loving','adore','affection','sweetheart','darling','cherish','beloved','romance',
    'kiss','embrace','tender','devotion','soulmate','warmth','caring',
    'crush','smitten','infatuated','babe','honey','boo','cuddle','snuggle','flirt','flirting',
    'romantic','valentine','partner',
    'عشق','دلبر','محبوب','دوست‌داشتن','عاشق','نازنین','دلتنگ','مهربان','صمیمی','محبت','دلداده',
    'head over heels','madly in love','deeply in love','crazy about','wild about',
    'falling for','into you','crazy for you','obsessed with','addicted to you',
    'you mean the world to me','you are my everything','you are my rock','you are my anchor',
    'you are my sunshine','you are my light','you are my heart','you are my soul',
    'my better half','my one and only','my true love','my soulmate',
    'my angel','my prince','my princess','my king','my queen',
    'puppy love','young love','first love','true love','eternal love',
    'unconditional love','endless love','deep love','passionate love','romantic love',
    'holding hands','walking together','sharing moments','making memories','building a life',
    'together forever','always and forever','through thick and thin','through good and bad',
    'in sickness and in health','for better or worse','till death do us part',
    'my heart belongs to you','my heart aches for you','my heart skips a beat',
    'butterflies in my stomach','heart racing','heart pounding','heart melting',
    'love at first sight','falling in love','falling deeper','falling harder',
    'you complete me','you make me whole','you make me better','you make me happy',
  ]},
  calm: { weight: 0.7, tense: -0.3, words: [
    'calm','peace','peaceful','serene','quiet','still','gentle','soft','tranquil','rest','resting',
    'breathe','ease','relax','relaxed','soothing','silence','stillness',
    'chill','chilling','mellow','laid-back','easygoing','unwind','unwinding','relaxing',
    'cozy','comfy','breezy','low-key',
    'آرام','آرامش','سکوت','ساکت','راحت','استراحت','نرم','ملایم','صلح','هدوء','سکون',
    'at ease','at peace','in peace','in harmony','in balance','in sync',
    'going with the flow','taking it easy','kicking back','hanging loose','chilling out',
    'decompressing','destressing','letting go',
    'deep breath','deep breaths','breathing easy','breathing calmly','centered',
    'grounded','rooted','anchored','stable','steady','solid','firm',
    'unshaken','unruffled','unflappable','cool headed','level headed',
    'clear minded','clear headed','focused','collected','composed','poised',
    'placid','halcyon','idyllic','pastoral','bucolic','picturesque',
    'hushed','mute','silent',
    'restful','calming','comforting',
    'meditative','contemplative','reflective','introspective','mindful',
    'zen','nirvana','euphoria','serenity','tranquility',
  ]},
  hope: { weight: 0.8, tense: -0.1, words: [
    'hope','hopeful','dream','dreaming','future','faith','believe','wish','light','promise',
    'grateful','gratitude','free','freedom','alive','beginning','new','grow','growth',
    'optimistic','upbeat','motivated','ambitious','driven','determined','striving','aspire',
    'امید','امیدوار','رویا','آینده','ایمان','آرزو','نور','شکرگزار','آزاد','زندگی','رشد','شروع',
    'looking forward','looking ahead','eyes on the prize','keeping my chin up',
    'staying positive','thinking positive','positive vibes','good vibes','high hopes',
    'dreaming big','aiming high','shooting for the stars','reaching for the moon',
    'the sky is the limit','nothing is impossible','anything is possible',
    'there is hope','there is light','there is a way','where there is a will there is a way',
    'every day is a new day','every day is a fresh start','today is a new day',
    'tomorrow is another day','better days ahead','brighter days ahead',
    'the best is yet to come','good things are coming',
    'something good is about to happen','something wonderful is about to happen',
    'believing in myself','trusting the process','trusting the journey',
    'having faith','keeping faith','staying faithful','remaining hopeful',
    'never giving up','never losing hope','never losing faith','never losing heart',
    'holding on','hanging in there','hanging tough','staying strong',
    'fighting the good fight','staying the course','keeping on keeping on',
    'one day at a time','step by step','little by little','bit by bit',
    'slowly but surely','eventually','in time','sooner or later','one day',
  ]},
  sadness: { weight: -1.0, tense: 0.1, words: [
    'sad','sadness','sorrow','grief','grieving','cry','crying','tears','weep','heartbroken',
    'lonely','alone','loneliness','empty','emptiness','hollow','loss','missing',
    'hurt','hurting','broken','depressed','blue','gloom','gloomy','melancholy','heavy',
    'غم','غمگین','اندوه','گریه','اشک','تنهایی','خالی','شکست','شکسته','از دست دادن',
    'دلتنگی','افسرده','سنگین','ملال','اندوهگین',
    'heart aches','heart hurts','heart is heavy','heart is broken','heart is shattered',
    'feeling down','feeling low','feeling sad','feeling hollow',
    'feeling lonely','feeling isolated',
    'feeling rejected','feeling ignored','feeling forgotten','feeling invisible',
    'world is gray','sky is gray','life is gray','everything is gray','nothing has color',
    'can\'t stop crying','can\'t stop tears','can\'t hold back tears','tears won\'t stop',
    'lumps in my throat','choking up','voice cracking','voice breaking',
    'heavy heart','heavy soul','heavy mind','heavy spirit','heavy shoulders',
    'weight of the world','weight on my chest','weight on my shoulders',
    'sinking feeling','pit in my stomach','knot in my throat','lump in my throat',
    'feeling glum','feeling morose','feeling dismal','feeling dreary',
    'feeling bleak','feeling desolate','feeling forsaken','feeling neglected',
    'in a dark place','in a funk','in a slump','in a rut','in a hole',
    'spirits are low','morale is low','energy is low','enthusiasm is low',
  ]},
  fear: { weight: -0.9, tense: 0.5, words: [
    'fear','afraid','scared','terrified','terror','dread','anxious','anxiety','worry','worried',
    'nervous','panic','threat','danger','unsafe','trembling','frightened','horror','nightmare',
    'ترس','ترسیده','وحشت','نگران','نگرانی','اضطراب','استرس','خطر','کابوس','لرزان','هراس',
    'on edge','on pins and needles','on tenterhooks','walking on eggshells',
    'stressed out','stressed to the max','under pressure','under the gun',
    'heart in my throat','heart in my mouth','stomach in knots','butterflies in stomach',
    'shaking like a leaf','trembling like a leaf','quivering','quaking','shivering',
    'cold sweat','clammy hands','sweaty palms','sweating bullets','breaking out in a sweat',
    'fight or flight','freeze response','paralyzed with fear','frozen in fear',
    'scared stiff','scared to death','scared out of my wits','scared senseless',
    'terrified out of my mind','petrified','horrified','aghast','appalled',
    'dreading it','not looking forward to it','worried sick','worried to death',
    'anxious about it','nervous about it','stressed about it','freaking out',
    'going crazy','losing my mind','spiraling','panicking',
    'short of breath','can\'t breathe','hyperventilating','gasping for air',
    'senses on high alert','hyperaware','hyper vigilant','on guard','on watch',
  ]},
  anger: { weight: -0.7, tense: 1.0, words: [
    'anger','angry','furious','fury','rage','mad','hate','hatred','resent','resentment',
    'bitter','bitterness','outrage','irritated','frustrated','frustration','scream','screaming',
    'fuck','fucking','fucked','shit','shitty','damn','dammit','hell','ass','asshole','bitch',
    'خشم','عصبانی','غضب','نفرت','کینه','خشمگین','عصبانیت','جنگ','هرج و مرج','وحشی','انفجار',
    'pissed off','pissed','livid','seething','boiling','fuming','raging','infuriated',
    'enraged','outraged','incensed','irate','wrathful','indignant','resentful',
    'fed up','sick and tired','had enough','done with this','over it',
    'at my wit\'s end','at the end of my rope','at the end of my tether',
    'losing my cool','losing my temper','blowing my top','blowing my lid',
    'seeing red','blood boiling','blood pumping','pulse racing',
    'snapping','going off','going ballistic','going ape',
    'throwing a fit','throwing a tantrum','having a meltdown','losing the plot',
    'busting my chops','getting on my nerves','rubbing me the wrong way','pushing my buttons',
    'under my skin','under my nails','in my face','in my grill','in my space',
    'back off','get out of my face',
    'take a hike','beat it','scram','vamoose','skedaddle','make like a tree',
  ]},
  dark: { weight: -0.8, tense: 0.4, words: [
    'dark','darkness','cold','coldness','death','dying','dead','despair','desperate','hopeless',
    'void','abyss','shadow','shadows','bleak','doom','suffering','pain','painful','wound','wounded',
    'تاریک','تاریکی','سرد','سرما','مرگ','مردن','ناامید','نومیدی','رنج','درد','زخم','سایه','تباهی',
    'no way out','no end in sight','no light at the end of the tunnel',
    'lost cause','dead end','hit a wall','hit rock bottom','hit the bottom',
    'at the end of the line','at the end of the road','at the end of my tether',
    'given up','given up hope','given up on life','given up on everything',
    'nothing matters','everything is pointless',
    'life is meaningless','life is empty','life is hollow',
    'living nightmare','waking nightmare','bad dream','dark dream','horror show',
    'going through hell','walking through fire','trapped in darkness','stuck in the dark',
    'drowning','sinking','falling','crumbling','collapsing','disintegrating',
    'broken beyond repair','shattered beyond repair','damaged beyond repair',
    'nothing left','nothing remains','nothing survives','nothing endures',
    'hollow inside','empty inside','dead inside','numb inside',
    'black hole','nothingness','oblivion','eternal darkness',
  ]},
  nostalgia: { weight: -0.2, tense: -0.1, words: [
    'remember','memory','memories','past','once','childhood','old','faded','distant',
    'longing','yearning','bittersweet','farewell','goodbye','gone','fading','nostalgia','nostalgic',
    'یاد','خاطره','خاطرات','گذشته','کودکی','دلتنگی','خداحافظ','رفته','محو','دور',
    'those were the days','the good old days','days of old','times gone by','gone but not forgotten',
    'throwback','blast from the past','taking a trip down memory lane',
    'reminiscing','recollecting','recalling','remembering','thinking back',
    'looking back','looking back on','harking back to','going back in time',
    'in those days','back in the day','once upon a time','a lifetime ago',
    'seems like yesterday','feels like a lifetime ago','ancient history',
    'old days','old memories','old friends','old haunts',
    'the way things were','how things used to be','how things were','the way it was',
    'miss the old days','miss the past','miss how things were','miss how it used to be',
    'fond memories','sweet memories','cherished memories','precious memories','treasured memories',
    'those days are gone','those times are gone','those moments are gone',
    'bittersweet memories','bittersweet feelings','bittersweet taste',
    'aching for the past','yearning for the past','longing for the past','hungering for the past',
    'ancient times','bygone era','bygone days','lost era',
  ]},
  vice: { weight: -0.3, tense: 0.2, words: [
    'smoke','smoking','cigarette','cigarettes','cigs','vape','vaping','drunk','wasted','booze',
    'beer','alcohol','hangover','buzzed','stoned','high','weed','joint','shots','bar','pub',
    'party',
    'سیگاری','دخانیات','مشروب','مست','مستی','خماری','هوس','وسوسه',
    'گناه','خطا','لغزش','اشتباه','تباهی','فساد','انحراف',
    'one more drink','one more round','one more shot','one more beer','just one more',
    'let\'s party','let\'s get wasted','let\'s get plastered','let\'s get hammered',
    'let\'s get tipsy','let\'s get sloshed','let\'s get loaded','let\'s get buzzed',
    'drowning my sorrows','drinking away the pain','numbing the pain',
    'letting loose','going wild','getting crazy','getting wild',
    'partying hard','having a wild night','painting the town red',
    'regretting','paying the price','reaping what i sowed',
    'too much','overdid it','went overboard','lost control',
    'couldn\'t stop','couldn\'t resist','couldn\'t help myself','weak moment',
    'guilty pleasure','bad habit','dirty habit','nasty habit','old habit',
    'addicted','hooked','can\'t quit',
    'one thing led to another','next thing i knew','before i knew it',
    'no self control','no willpower','no discipline','no restraint',
  ]},
  casual: { weight: 0, tense: 0, words: [
    'dude','bro','man','guy','buddy','pal','yo','hey','sup','nah','yeah','yep','nope',
    'okay','fine','sure','cool','awesome','whatever',
    'omg','lol','lmao','tbh','imo','fr','no cap','low key','high key','deadass','bet',
    'راستی یه چیزی بگم','ببین چی میخوام بگم','یه چیزی یادم اومد',
    'just saying','no worries','no big deal','no problem','no sweat','no bother',
    'my bad','my fault','my mistake','i\'m sorry','sorry about that','sorry dude',
    'what\'s up','how\'s it going','how are you','how\'s life','how\'s things',
    'long time no see','been a while','it\'s been forever','what\'s new',
    'not much','same old','same old same old','nothing new','just chilling',
    'hanging out','hanging around','killing time','biding my time','just vibing',
    'catch you later','talk to you later','see you later','peace out','i\'m out',
    'take care','stay safe','be good','don\'t be a stranger','keep in touch',
    'for real','for sure','for real tho','i swear','truth be told',
    'i guess','i suppose','i reckon','i think','i believe','in my opinion',
    'anyway','anyways','moving on','speaking of which','by the way','that said',
    'kind of','sort of','sorta','kinda','essentially',
    'i mean','you know','like i said','as i was saying',
  ]},
  confusion: { weight: 0, tense: 0.3, words: [
    'confused','confusing','puzzled','puzzling','bewildered','baffled','perplexed','lost',
    'unclear','ambiguous','ambivalent','torn','undecided','second guessing',
    'گیج','سردرگم','مشوش','متحیر','حیران','سرگردان','دودل','مردد',
    'نامطمئن','نامشخص','مبهم','گنگ','پیچیده','دشوار','سخت',
    'mind is boggled','brain is fried','brain is melting','head is spinning',
    'can\'t make heads or tails','can\'t wrap my head around','can\'t grasp','can\'t comprehend',
    'don\'t get it','don\'t understand','don\'t follow','don\'t see','don\'t know',
    'no clue','no idea','no concept','no grasp','no understanding',
    'what the hell','what on earth','what in the world','what the heck',
    'is it this or that','is it a or b','can\'t decide','can\'t choose','can\'t tell',
    'on the fence','sitting on the fence','can\'t make up my mind','unresolved',
    'mixed signals','mixed messages','conflicting info','contradictory information',
    'over my head','above my pay grade','beyond me',
    'lost the plot','lost my train of thought','lost track','lost where i was',
    'back to square one','starting over','starting from scratch','starting from the beginning',
    'where was i','what was i saying','what was i thinking','what was the point',
  ]},
  surprise: { weight: 0.4, tense: 0.5, words: [
    'surprised','shocked','stunned','astonished','amazed','astounded','taken aback',
    'wow','whoa','holy cow','oh my god','unbelievable','mind blown',
    'jaw dropped','flabbergasted','gobsmacked','blindsided','unexpected',
    'محاله این','غیرممکنه به نظرم','نمیشه باورش کرد','هیچ‌وقت فکرشو نمیکردم',
    'no way','shut up','get out','are you serious','are you kidding me',
    'you\'re kidding','you\'re joking','you\'re pulling my leg','you\'re messing with me',
    'i can\'t believe it','i don\'t believe it','i refuse to believe it','unreal',
    'out of nowhere','out of the blue','out of thin air','completely unexpected',
    'never in a million years','who would have thought','who would have guessed',
    'plot twist','game changer','life changer','eye opener','wake up call',
    'jaw on the floor','jaw hit the floor','eyes popped out','eyes wide open',
    'blew my mind','blew me away','knocked my socks off','took my breath away',
    'dumbfounded','stupefied','thunderstruck',
    'mind boggling','mind blowing','mind numbing','brain melting','head exploding',
    'unprecedented','unheard of','unimagined','unforeseen','unanticipated',
  ]},
};
